### ISSUE TITLE
Console output in Farm Mode does not expose Request Hosts

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-server#132]
As a wiki farm operator, during debugging I want to distinguish which requests target which domain. Currently it is not possible to tell which hosts the process output refers to:

```
owner: 
[ 'add-text' ]
starting plugin wiki-plugin-plugmatic
GET /favicon.png?replaceTemp 200 655 - 1.392 ms
HEAD / 302 86 - 2.673 ms
[ 'welcome-visitors' ]
HEAD /welcome-visitors.html 200 4093 - 21.731 ms
removing sitemap from memory
rejecting /page/welcome-visitors/action
PUT /page/welcome-visitors/action 403 9 - 2.818 ms
Logout...
GET /logout 200 2 - 3.202 ms
```

**Comment by paul90** [comment]
A nice little exercise for somebody, the associated lines of code in the server are https://github.com/fedwiki/wiki-server/blob/master/lib/server.coffee#L178-L180

**Comment by WardCunningham** [comment]
The "forman" job control software does a good job of interleaving log output.

![foreman_screenshot_1](https://cloud.githubusercontent.com/assets/12127/26481310/0c4a639a-4195-11e7-8dde-d7275c7090cf.png)

I suggest color coding requests from a specific site so as to distinguish it from others and system messages which deserve their own color.

**Comment by almereyda** [comment]
Can't wait to test it!

Sorry I didn't figure it out earlier.

Maybe I'm now experienced enough to add these colours, if not included in the recent iteration?
