### ISSUE TITLE
Let's be clear who owns each wiki

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-server#14]
We're not the usual service with lots of users. That means the usual login workflow is confusing to visitors. Let's make the owner of claimed sites show the owners name like this:

    ward can (Log In)
    ward@c2.com can (Log Out)

We already to this second form. The first form makes it clear that only one person who is not you can login.

In the event that nobody has yet claimed the site then the eye-catching persona login is appropriate:

    [ Login with your email >

I've revised the welcome-visitors text to mention login as part of the template prompts, not body text that has to be discarded to make a site make sense to visitors.

**Comment by paul90** [comment]
Not sure why this was left open, closing...
