### ISSUE TITLE
CLI option for $DATABASE_URL formatted DB credentials

### ISSUE THREAD

**Issue by troytop** [fedwiki/wiki-server#29]
Heroku, Stackato, and other Platform-as-a-Service environments expose database credentials in a $DATABASE_URL (or similar) environment variable with a format like:

 db-protocol://username:password@hostname-or-ip:port/db-name

It varies a bit depending on the data store you are connecting to. For example, Stackato exposes this to my app:

REDIS_URL=redis://user:a859eb1b-56cf-433b-aad8-0e5a502d00a6@10.253.26.75:5101/

It would be nice to support this format with a '--db-url' (or similar) CLI option for server.js. That way, I could start the server with:

  node server.js --port $PORT --db-url $REDIS_URL

**Comment by paul90** [comment]
Closing, don't think this was addressed when the DB code was pulled out into plugins - but they have other more important deficiencies that will need to be addressed, such as not working in farm mode, if anybody want to use them.
