### ISSUE TITLE
image upload fails ... or not? timeouts, claiming, accessing.

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-server#35]
### Dear people,

in my farm, which is nginx reverse proxy'd, I do have several sites behind a simple basic authentification and one public site.

The ones being auth'd are usually non-claimed, as they are collectively edited wikis. (Yes, I do know this doesn't fit the federation thought, but I'm working myself slowly into the matter - not to talk about the ones I'm forcing to use it ;) )

As mentionned in #24 , I use a rough and insecure workaround to access the wikis directly. (If I don't put the reverse proxy in front, bots banging on my server would create several wikis just by sending random HTTP HOST headers.)

The public wiki is claimed, so no visitor is able to change anything.

---

#### *Question*:

> ~~Why does image uploading work on the public wiki, even behind the proxy, but not on the "hidden" ones, even when accessed directly?~~

> I've also claimed one of the latter, just to see that it doesn't change a bit. How to revert that?

I'll update this issue soon to provide further details on server logs, configuration examples and different error messages from nginx and/or wiki-client.

Further on, after having found the actual wiki's log instead of nginx' ones, I found the entry of the accepted file. It did accept PNG (10 KiB) but rejected JPG (110 KiB). Which I could reproduce on one of the auth'd wikis. 

---

#### *Finally*:

> Is there some kind of (undocumented) size limit for the base64 data: array? Or just my deploy that goes wild?

Nightly greetings from Berlin,

### Jon

---

PS : next idea to work on : fedwiki as CMS w/ something like https://github.com/pure/pure or https://github.com/wycats/handlebars.js : what do you think? (similiar to http://fargo.io + https://github.com/scripting/trex, or gh-pages + octopress)

PPS : there's something going on with liquid multi column layouts . just look at https://ginkoapp.com and think of the fedwiki. then have a look at https://trello.com and rethink the wiki again. in the last step let's think of structured data like in https://fargo.io . there (like Bob Ross would say.) ... is ... something. [ I did also like the https://unhosted.org and http://remotestorage.io references I've found the other day in one of the federated wikis. ]

**Comment by paul90** [comment]
This issue was resolved by adding a configuration item to the server to allow the site owner to specify a max upload size limit.
