### ISSUE TITLE
trouble diagnosing persona issues

### ISSUE THREAD

**Issue by pmuellr** [fedwiki/wiki-server#36]
I'm running a server, but not able to get the persona login to work.  I can't get anything other than failure while logging in.

I've used persona on other sites, so I know my "basic" persona skillz are ok - none-the-less, this is most probably an error on my part.  Or is some configuration required which isn't I didn't notice in the docs?

Anyhoo, before I dive in, I'll just note that there aren't really any good diagnostics for this particular failure.  Here are the symptoms:

* a red list item at the top of the browser page which says `Error on /persona_login: FAIL` in red

* Chrome DevTools shows a POST to https://<server>/persona_login which is getting a  401 (Unauthorized).  The form data posted is the persona assertion (long), the response pay load is `FAIL`.

* the server prints the following:

```
[ 'isAuthenticated? owner=',
  '',
  'req.session.email=',
  undefined,
  false ]
```

**Comment by hallahan** [comment]
I have gotten Persona working with wiki running port 3000 and NGINX reverse proxying via 80. The trick is that you MUST STATE BOTH 1) the port and 2) the intended URL in your startup params:

```
./index.js -p 3000 -u http://wiki.theoutpost.io
```

Missing either of those params makes login fail.

**Comment by hallahan** [comment]
Hmm, I think I tricked it into working, but it is not working any more. I have reverted to only logging in when going in on port 3000. With that in mind, I need to start the server as follows:

```
./index.js -p 3000 -u http://wiki.theoutpost.io:3000
```

And only log in via port 3000

**Comment by almereyda** [comment]
I have two wiki farms running.

---

First one is started as an upstart service

```
description "sfw farm"
author      "kvz + almereyda"

# used to be: start on startup
# until we found some mounts weren't ready yet while booting:
start on runlevel [235]
stop on runlevel [016]

# Automatically Respawn:
respawn
respawn limit 99 5

export HOME="/root"
NOW=$(date +"%Y-%m-%d")

script
  source ~/.nvm/nvm.sh
  nvm use 0.10
  mkfifo /var/www/wikifarm/logs/fifo
  ( logger -t wikifarm </var/www/wikifarm/logs/fifo & )
  exec >/var/www/wikifarm/logs/fifo
  rm /var/www/wikifarm/logs/fifo
  exec wiki --config /var/www/wikifarm/wikifarm.json 2>> /var/www/wikifarm/logs/wikifarm.$NOW.log
end script
```

The `wikifarm.json` as follows

```
{
	"host": "127.0.0.1",
	"data": "/var/www/wikifarm/data/",
	"farm": true
}
```

My public wikifarm at `*.wiki.allmende.io* uses the following nginx config

```
server {
	listen 80;
	server_name .wiki.allmende.io;

	access_log  /var/www/wikifarm/wiki.allmende.io.access.log;
	error_log  /var/www/wikifarm/wiki.allmende.io.error.log;

client_body_in_file_only clean;
client_body_buffer_size 32K;

client_max_body_size 10M;

sendfile on;
send_timeout 300;


	location / {

		proxy_pass http://127.0.0.1:3000;
		proxy_redirect off;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $remote_addr;

	client_max_body_size       10M;
	client_body_buffer_size    32k;
	client_body_in_file_only clean;

	proxy_connect_timeout 300;
	proxy_send_timeout 300;
	proxy_read_timeout 300;

	proxy_buffer_size 4k;
	proxy_buffers 4 32k;
	proxy_busy_buffers_size 64k;
	proxy_temp_file_write_size 64k;


	}

}
```


I believe it makes sense to rely on the npm `wiki` metapackage instead of running `wiki-node-server` alone. Persona works just fine there. Try it out by creating a new wiki and claiming it.

---

Persona does not work for TLS + HTTP basic auth secured wikis, as the callback cannot pass the authentication. But local wikis, DNSed in my private router, or just by `/etc/hosts`, also successfully return the callback.

I will update this thread with the respective systemd, farm and nginx config.

**Comment by hallahan** [comment]
I think I figured out what's going on here. It's not the reverse proxy. I'm using pm2 (similar to upstart) to keep the process alive, but the command line arguments are not passing through.

Everything works fine when I manually go in the command line and start it as such:

```
./index.js -p 3000 -u http://wiki.theoutpost.io
```

Then, I can use persona just fine through NGINX.

So, I need to figure out how to start the wiki using a "config file" rather than command line args. Are there any instructions on how to do this? Do I make some sort of config.js file and put it somewhere?

**Comment by WardCunningham** [comment]
Server options are described in the ReadMe.
https://github.com/fedwiki/wiki-node/blob/master/ReadMe.md#server-options

A config file might look like this:
```
{
    "farm": true,
    "data": "/Users/ward/Smallest-Federated-Wiki/data/farm"
}
```

**Comment by hallahan** [comment]
Cool. I figured out that if I have a config file for pm2, I can do `pm2 start config_file.js`. Then I make my config file have this:

```js
{
  "apps" : [{
    "name"        : "wiki",
    "script"      : "/usr/lib/node_modules/wiki/index.js",
    "args"        : ["-p", "3000", "-u", "http://wiki.theoutpost.io"],
  }]
}
```

Doing this resolves my issue. 

Now my question is: How do I get in neighborhoods so my wiki can be discovered by your wikis? Sorry, I've been out of the loop for a while...

**Comment by WardCunningham** [comment]
You can put the config file in the root or current working directory. Then you need not specify --config.

I have two sites for you listed in sites.fed.wiki.org.

![image](https://cloud.githubusercontent.com/assets/12127/5994265/37a2165e-aa21-11e4-917a-25d172b2ba8d.png)

Well documented SEO techniques work too.

**Comment by paul90** [comment]
With pm2 you need to pass the parameters to your application slightly differently, the following example is from the PM2 advanced readme:
```
$ pm2 start app.js -- -a 23  # Pass arguments '-a 23' argument to app.js script
```
Any parameters after the ` -- ` will be passed to the application.

**Comment by almereyda** [comment]
@paul90 is right here, because it also allows you to pass custom parameters like

    $ pm2 start app.js --name "My Wikifarm" -- --config wikifarm.json

A while ago another process manager for Node appeared on the scene, which seems pretty interesting to discover https://github.com/tableflip/boss
