### ISSUE TITLE
TLS/SSL Support

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-server#53]
Instead of using an TLS/SSL Proxy, that breaks the current implementation of Federation, I'm investigating ways to use Node's [https module](http://nodejs.org/api/https.html#https_class_https_agent) for integrated security support.

Appearantly, *Public Key Client Authentication + HTTP fallbacks*, if needed, will have to be implemented.

This is aimed at **private wikis**, that are directly connected to the internet. Having federation working between them is needed for corporate environments.

I believe that this requires a fork and an extension of [the library itself](https://github.com/fedwiki/wiki-node-server/tree/master/lib), but wonder if the current *plugin-engine* would also be able to handle this? Reading of `pluginsFactory` in the code doesn't give me the impression.

Any **additions / thoughts / concerns / ideas** are highly appreciated!

**Comment by WardCunningham** [comment]
Do these certs allow wildcards?

**Comment by paul90** [comment]
No, *Let's encrypt* have said that they will not be supporting wildcard at launch. There is an closed issue no.66 asking that question that includes this answer (sure this was something we touched on in a hangout a little while ago):
> we will support names with multiple Subject Altnerative Names (SANs or UCC certificates in the CA nomenclature) at launch.

But that is probably only of limit help for those who only infrequently create new sites. Though it might be enough to make a start, but without wildcards, as long as there is something more concrete about when they will be adding support.

**Comment by paul90** [comment]
Closing this issue as a lot has changed in the last 2+ years.

We now have Let's Encrypt, and certificates on demand (automatic HTTPS) in caddy server. But, we also have browsers blocking loading plain http content when using a https origin. Plus a host of other interesting issues/opportunities.
